### ISSUE TITLE
Decoding Issue

### ISSUE THREAD

**Issue by redlean91** [MZommer/LYNTml#1]
![image](https://user-images.githubusercontent.com/88703078/230765720-14f73932-97f9-4b51-a784-2b296b617087.png)
When i go to deserialize some maps this error pops up.
The Party Master routines dont work and its ok but as for now on this list ive got some maps it didint deserialize.
![image](https://user-images.githubusercontent.com/88703078/230765753-ce6e7fd7-a230-4f55-b4d5-73593a342b40.png)

**Comment by MZommer** [comment]
Should be fixed with the last commit.
