### ISSUE TITLE
struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by techyyyt** [MZommer/LYNTml#2]
I am getting the following error if I try to extract WiiU Just Dance 4 files:
![image](https://github.com/MZommer/LYNTml/assets/132097847/0d6bae45-0d15-46b1-bd32-b97c5b0c32b7)

The PS3 version is throwing a utf-8 error, the Xbox360 version is throwing 'ValueError: subsection not found'

**Comment by MZommer** [comment]
Hi, you are opening the BF (BigFile) file, you need to extract it, inside of this bundle are the files of the game.

**Comment by techyyyt** [comment]
Ah, thank you. Do I need to extract it with a bms script?

Matias Zommer ***@***.***> ezt írta (időpont: 2023. jún. 6.,
K 0:40):
