### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by smpial** [MZommer/LYNTml#4]
I tried to put JD4.BF file in input folder and run BinaryFinder.py, output folder is empty. Then I tried to put all JD4.BF files in input folder - same result. I'm doing something wrong? My input folder:
![image](https://github.com/MZommer/LYNTml/assets/66345743/bdd53884-e52c-4a4e-acec-ff0741e57e94)
![image](https://github.com/MZommer/LYNTml/assets/66345743/ce2122bd-77e0-4f8f-a24d-0082d9950e5b)
and total 5508 files

**Comment by pedrosouza9966** [comment]
you only need to put files that ENDS with `.bin` on the input folder, and then run BinaryFinder.py. After that, move the output bin files to the input folder (delete them first) and run Deserializer.py.

**Also, not all timelines work with LyNTML**

**Comment by MZommer** [comment]
@smpial Make sure to be decompressing the BF file the correct way, the details are on the readme.
